### ISSUE TITLE
Buscar Banca -  ID da banca e Nome do Aluno

### ISSUE THREAD

**Issue by brunopnhr** [psbarros/sysicomp#11]
- O sistema apresenta erro ao buscar banca usando o "id" da banca como parâmetro 
- O sistema apresenta erro ao buscar banca usando o "nome do aluno"  como parâmetro 

Passos para reprodução:

1.Acessar página inicial.
2.Acessar seção “Professor”.
3.Clicar em aba “Gerenciar Defesas”.
4.Clicar em aba ”Gerenciar Banca”.
5.Preencher o campo: Banca com  int x.
6.Visualizar Banca com todos os dados relacionados ao int x.
7.Clicar em aba “Gerenciar Defesas”.
8.Clicar em aba ”Gerenciar Banca”.
9.Preencher o campo: Aluno com String  y.
10.Visualizar Banca com todos os dados relacionados ao String y.
11.Fim do Caso de teste.

**Comment by JonasSsdi** [comment]
filtro corrigido, agora ele busca pelo nome da tabela e do atributo, assim evitando o erro de duplicidade na busca
