### ISSUE TITLE
Agendar defesas não tá aparecendo no perfil do "PROFESSOR"

### ISSUE THREAD

**Issue by gercidaralira** [psbarros/sysicomp#3]
Deve ser adicionado o trecho de código ao left.php/left-sample.php na parte do professor, para poder aparecer. 

Passos para reprodução:

1.Acessar página inicial.
2.Clicar em menu lateral “Professor”.
3.Clicar em Aba “Gerenciar Defesa”.
4.Mostrar aba “Agendar Defesa”.
5.Fim do caso de teste. 

Para correção acrescentar:

 ``
['label' => 'Gerenciar Defesas',
                    'icon' => 'fa fa-calendar-check-o',
                    'url' => '#',
                    'visible' => Yii::$app->user->identity->checarAcesso('secretaria'),
                    'items' => [
                      ['label' => 'Agendar Defesas', 'icon' => 'fa fa-list', 'url' => ['agendar-defesa/create'], 'visible' => Yii::$app->user->identity->checarAcesso('secretaria')||Yii::$app->user->identity->checarAcesso('administrador'),],
                    ],
                ],
``

**Comment by DanGodinho** [comment]
Correção feita !
