### ISSUE TITLE
Criar Banca - Restringir que o mesmo professor ocupe diferentes cargos na mesma banca.

### ISSUE THREAD

**Issue by brunopnhr** [psbarros/sysicomp#7]
A banca não é criada, mas o sistema apresenta erro. 
Deve exibir uma mensagem e solicitar a  alteração dos campos em questão.

Passos para reprodução:

1.Acessar página inicial.
2.Acessar seção “Professor”.
3.Clicar em aba “Gerenciar Defesas”.
4.Clicar em aba ”Gerenciar Banca”.
5.Clicar em botão “Criar Nova Banca”.
6.Preencher campos: Presidente da Banca, Componente 2, Componente 3, com o mesmo Nome Membro.
7.Clicar em botão “Salvar”.
8.Mostrar mensagem de erro: “Banca não criada! Os membros devem ser diferentes um do outro!”.
9.Fim do caso de teste.

**Comment by JonasSsdi** [comment]
o sistema agora da uma mensagem de erro na tela informando que os membros devem ser diferentes
