### ISSUE TITLE
Buscar Defesa - Conceito Não Julgado

### ISSUE THREAD

**Issue by brunopnhr** [psbarros/sysicomp#8]
Inserir o  conceito "Não Julgado" aos filtros de busca.

Passos para reprodução:

1.Clicar em aba ”Gerenciar Defesas”.
2.Clicar em aba “Listar todas as defesas”.
3.Visualizar página Lista de Defesas.
4.Clicar no Combo box com a tag “Conceito”.
5.Selecionar a opção: “Não julgado”.
6.Visualizar página Lista de Defesas com Conceito: “Não julgado”.
7.Fim do caso de teste.

**Comment by PriscilaSCosta** [comment]
Não realiza busca por conceito "Não julgado", mostra página com nenhum resultado encontrado.

**Comment by PriscilaSCosta** [comment]
Filtro funcionando corretamente.
