### ISSUE TITLE
Criar Banca de Mestrado/Doutorado - Restringir quantidade de Membros

### ISSUE THREAD

**Issue by brunopnhr** [psbarros/sysicomp#9]
- As bancas de mestrado devem ter no MINIMO 3 MEMBROS
- As bancas de doutorado (Q1 e Q2) devem ter no MINIMO 3 MEMBROS
- As bancas de doutorado (Defesa) devem ter no MINIMO 5 MEMBROS

Passos para reprodução:

1.Acessar página inicial.
2.Acessar seção “Professor”.
3.Clicar em aba “Gerenciar Defesas”.
4.Clicar em aba ”Gerenciar Banca”.
5.Clicar em botão “Criar Nova Banca”.
6.Preencher campos: Presidente da Banca, Componente 2.(Utilizar mesma quantidade para bancas de Doutorado Q1 e Q2).
7.Clicar em botão “Salvar”.
8.Visualizar mensagem de erro: Banca não Criada! Número de membros inválido!! Mestrado no mínimo 3 membros , Doutorado Q1 e Q2, no mínimo 3 membros e Defesa de Doutorado no mínimo 5 Membro.
9.Visualizar página “Criar Banca” sem alterações.
10.Clicar em botão “Criar Nova Banca”.
11.Preencher campos: Presidente da Banca, Componente 2, Componente 3.(Utilização para Defesa).
12.Clicar em botão “Salvar”.
13.Visualizar mensagem de erro: Banca não Criada! Número de membros inválido!! Mestrado no mínimo 3 membros , Doutorado Q1 e Q2, no mínimo 3 membros e Defesa de Doutorado no mínimo 5 Membro.
14.Visualizar página “Criar Banca” sem alterações.

**Comment by JonasSsdi** [comment]
adicionado um campo onde o usuário seleciona um tipo de banca e com isso o filtro de numeros de membros é ativado

**Comment by brunopnhr** [comment]
Após mudanças, este problema que já havia sido corrigido, voltou a acontecer.
Os passos para a reprodução estão escritos acima
